spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/payment_db
    username: postgres
    password: root9999

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false

    properties:
      hibernate:
        format_sql: false

  jackson:
    serialization:
      indent-output: true

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.orm.jdbc.bind: OFF
    org.hibernate.tool.schema: OFF

server:
  port: 8080