            - name: Maven Build Action
  # You may pin to the exact commit or the version.
  # uses: dienha93/maven-actions@09ffbc6e105db67bac5ed3c7ee28ce5fd651c5d9
  uses: dienha93/maven-actions@v1.1.0
  with:
    # Maven version to use
    maven-version: # optional, default is 3.9.5
    # Java version to use
    java-version: # optional, default is 17
    # Java distribution to use
    java-distribution: # optional, default is corretto
    # Additional Maven arguments
    maven-args: # optional, default is 
    # Maven operation to perform (e.g., "package", "test", "install")
    operation: # default is package
    # Working directory for Maven commands
    working-directory: # optional, default is .
    # Path to Maven settings.xml file
    settings-file: # optional, default is 
    # Enable Maven dependency caching
    cache-enabled: # optional, default is true
    # Force to install Java version
    force-install: # optional, default is false
          
